name: frontend-build-deploy
run-name: ${{ github.actor }} - frontend-build-deploy
on: [ push]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          cd ./patient_frontend
          npm build

      - name: Testing
        run: |
          cd ./patient_frontend
          npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./patient_frontend
          file: ./patient_frontend/Dockerfile
          push: true
          tags: docker.io/devve00/patient_journal_test:patient_frontend